// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Link struct {
	ID      int     `json:"id"`
	Title   string  `json:"title"`
	Address *string `json:"address"`
	UserID  *int    `json:"userId"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewLink struct {
	Title   string `json:"title"`
	Address string `json:"address"`
	UserID  int    `json:"userId"`
}

type NewProject struct {
	Name     string  `json:"name"`
	Quantity int     `json:"quantity"`
	Buget    float64 `json:"buget"`
}

type NewRefreshToken struct {
	Token string `json:"token"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Project struct {
	ID       int      `json:"id"`
	Name     string   `json:"name"`
	Quantity *int     `json:"quantity"`
	Buget    *float64 `json:"buget"`
	Users    []*User  `json:"users"`
}

type User struct {
	ID       int        `json:"id"`
	Name     string     `json:"name"`
	Links    []*Link    `json:"links"`
	Projects []*Project `json:"projects"`
}
